# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e71322090fb1eb20b9d943a5a96c945d75ffa09b2dbe86500b6d468ccc9cc6910f78fb71043140183f3b0f2ffa8cb2e3e73153582db5ee0ef2763196f7d6a15

test:
  secret_key_base: d699932bf78ad0f60b36428d36db101218c3b5b0855003e9e8ce70fa4798cc2fc951fc1aade9e7a1d0783260771c8bf4647af961ad923b9f2e5305ddbe4ea7df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
